"""System state management for multi-agent orchestration.

The state tracks:
- User context (user_id, session_id)
- Learning progress (current_lesson, learned_items)
- Conversation flow (history, pending_exercise, last_agent)
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass
class Message:
    """A message in the conversation."""

    role: str  # "user", "agent1", "agent2", "agent3", "system"
    content: str
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class Exercise:
    """An exercise generated by Agent 3."""

    exercise_id: str
    exercise_type: str  # "translation", "multiple_choice", etc.
    question: str
    answer: str
    difficulty: str  # "beginner", "intermediate", "advanced"
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class SystemState:
    """
    Global state for the multi-agent teaching system.

    This state is passed between agents and persists across conversation turns.

    Flow:
    1. User message → Agent 1 (Teaching) updates state
    2. Agent 1 needs exercise → Agent 3 (Content) generates exercise
    3. User submits answer → Agent 2 (Grading) validates answer
    4. Grading result → Agent 1 (Feedback) provides feedback
    """

    # User context
    user_id: str
    session_id: str

    # Learning progress
    current_lesson: int = 1
    current_mode: str = "vocabulary"  # "vocabulary" or "grammar"
    learned_items: list[str] = field(default_factory=list)
    lesson_history: list[dict[str, Any]] = field(default_factory=list)

    # Conversation state
    conversation_history: list[Message] = field(default_factory=list)
    pending_exercise: Exercise | None = None
    awaiting_user_answer: bool = False

    # Agent routing
    last_agent: str = ""  # "agent1", "agent2", "agent3"
    next_agent: str = "agent1"  # Default: start with teaching agent

    # Session metadata
    session_start_time: datetime = field(default_factory=datetime.now)
    total_exercises_completed: int = 0
    total_correct_answers: int = 0

    def add_message(self, role: str, content: str, metadata: dict | None = None) -> None:
        """Add a message to conversation history."""
        message = Message(role=role, content=content, metadata=metadata or {})
        self.conversation_history.append(message)

    def set_pending_exercise(self, exercise: Exercise) -> None:
        """Set an exercise that awaits user response."""
        self.pending_exercise = exercise
        self.awaiting_user_answer = True

    def clear_pending_exercise(self) -> None:
        """Clear the pending exercise after user answers."""
        self.pending_exercise = None
        self.awaiting_user_answer = False

    def add_learned_item(self, item: str) -> None:
        """Add a vocabulary word or grammar concept to learned items."""
        if item not in self.learned_items:
            self.learned_items.append(item)

    def record_exercise_result(self, correct: bool) -> None:
        """Record the result of an exercise."""
        self.total_exercises_completed += 1
        if correct:
            self.total_correct_answers += 1

    def get_accuracy(self) -> float:
        """Calculate overall accuracy percentage."""
        if self.total_exercises_completed == 0:
            return 0.0
        return (self.total_correct_answers / self.total_exercises_completed) * 100

    def to_dict(self) -> dict[str, Any]:
        """Serialize state to dict for persistence."""
        return {
            "user_id": self.user_id,
            "session_id": self.session_id,
            "current_lesson": self.current_lesson,
            "current_mode": self.current_mode,
            "learned_items": self.learned_items,
            "lesson_history": self.lesson_history,
            "pending_exercise": self.pending_exercise.__dict__ if self.pending_exercise else None,
            "awaiting_user_answer": self.awaiting_user_answer,
            "last_agent": self.last_agent,
            "next_agent": self.next_agent,
            "total_exercises_completed": self.total_exercises_completed,
            "total_correct_answers": self.total_correct_answers,
            "session_start_time": self.session_start_time.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SystemState":
        """Deserialize state from dict."""
        state = cls(
            user_id=data["user_id"],
            session_id=data["session_id"],
            current_lesson=data.get("current_lesson", 1),
            current_mode=data.get("current_mode", "vocabulary"),
            learned_items=data.get("learned_items", []),
            lesson_history=data.get("lesson_history", []),
            awaiting_user_answer=data.get("awaiting_user_answer", False),
            last_agent=data.get("last_agent", ""),
            next_agent=data.get("next_agent", "agent1"),
            total_exercises_completed=data.get("total_exercises_completed", 0),
            total_correct_answers=data.get("total_correct_answers", 0),
        )

        # Restore conversation history
        if "conversation_history" in data:
            history = data["conversation_history"]
            if history and isinstance(history[0], Message):
                # Already Message objects (from LangGraph)
                state.conversation_history = history
            elif history and isinstance(history[0], dict):
                # Dicts that need conversion
                state.conversation_history = [Message(**msg) for msg in history]

        # Restore pending exercise
        if data.get("pending_exercise"):
            exercise_data = data["pending_exercise"]
            if isinstance(exercise_data, Exercise):
                state.pending_exercise = exercise_data
            else:
                state.pending_exercise = Exercise(**exercise_data)

        # Restore session start time
        if "session_start_time" in data:
            start_time = data["session_start_time"]
            if isinstance(start_time, str):
                state.session_start_time = datetime.fromisoformat(start_time)
            elif isinstance(start_time, datetime):
                state.session_start_time = start_time

        return state
