"""System state management for multi-agent orchestration.

The state tracks:
- User context (user_id, session_id)
- Learning progress (current_lesson, learned_items)
- Conversation flow (history, pending_exercise, last_agent)
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass
class Message:
    """A message in the conversation."""

    role: str  # "user", "agent1", "agent2", "agent3", "system"
    content: str
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class Exercise:
    """An exercise generated by Agent 3."""

    exercise_id: str
    exercise_type: str  # "translation", "multiple_choice", etc.
    question: str
    answer: str
    difficulty: str  # "beginner", "intermediate", "advanced"
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class SystemState:
    """
    Global state for the multi-agent teaching system.

    This state is passed between agents and persists across conversation turns.

    Flow:
    1. User message → Agent 1 (Teaching) updates state
    2. Agent 1 needs exercise → Agent 3 (Content) generates exercise
    3. User submits answer → Agent 2 (Grading) validates answer
    4. Grading result → Agent 1 (Feedback) provides feedback
    """

    # User context
    user_id: str
    session_id: str

    # Learning progress
    current_lesson: int = 1
    current_mode: str = "vocabulary"  # "vocabulary" or "grammar"
    # NOTE: Treat `learned_items` as read-only outside this class.
    # Use the helper methods `add_learned_item`, `remove_learned_item`, and
    # `clear_learned_items` to keep `_learned_items_set` in sync.
    learned_items: list[str] = field(default_factory=list)
    _learned_items_set: set[str] = field(default_factory=set, repr=False)  # For O(1) lookup
    lesson_history: list[dict[str, Any]] = field(default_factory=list)

    # Conversation state
    conversation_history: list[Message] = field(default_factory=list)
    pending_exercise: Exercise | None = None
    awaiting_user_answer: bool = False

    # Agent routing
    last_agent: str = ""  # "agent1", "agent2", "agent3"
    next_agent: str = "agent1"  # Default: start with teaching agent

    # Content caching (Agent 3)
    cached_vocab_words: list[dict[str, Any]] = field(default_factory=list)
    cached_grammar_content: dict[str, Any] = field(default_factory=dict)
    lesson_initialized: bool = False

    # Grading pre-loading (Agent 2)
    preloaded_grammar_rules: dict[str, Any] = field(default_factory=dict)

    # Session metadata
    session_start_time: datetime = field(default_factory=datetime.now)
    total_exercises_completed: int = 0
    total_correct_answers: int = 0

    def add_message(self, role: str, content: str, metadata: dict | None = None) -> None:
        """Add a message to conversation history."""
        message = Message(role=role, content=content, metadata=metadata or {})
        self.conversation_history.append(message)

    def set_pending_exercise(self, exercise: Exercise) -> None:
        """Set an exercise that awaits user response."""
        self.pending_exercise = exercise
        self.awaiting_user_answer = True

    def clear_pending_exercise(self) -> None:
        """Clear the pending exercise after user answers."""
        self.pending_exercise = None
        self.awaiting_user_answer = False

    def add_learned_item(self, item: str) -> None:
        """Add a learned item, keeping both the list and set in sync.

        This should be the only way new items are added from outside this class.
        Uses O(1) deduplication via the internal set.
        """
        if item in self._learned_items_set:
            return
        self.learned_items.append(item)
        self._learned_items_set.add(item)

    def remove_learned_item(self, item: str) -> None:
        """Remove a learned item, keeping both the list and set in sync.

        Safe to call even if the item is not present.
        """
        if item not in self._learned_items_set:
            return

        self._learned_items_set.remove(item)
        try:
            self.learned_items.remove(item)
        except ValueError:
            # Fallback: if the list somehow got out of sync, resync from the set.
            self.learned_items = [i for i in self.learned_items if i != item]
            # Ensure set stays correct if there were duplicates.
            self._learned_items_set = set(self.learned_items)

    def clear_learned_items(self) -> None:
        """Clear all learned items from both the list and set."""
        self.learned_items.clear()
        self._learned_items_set.clear()

    def record_exercise_result(self, correct: bool) -> None:
        """Record the result of an exercise."""
        self.total_exercises_completed += 1
        if correct:
            self.total_correct_answers += 1

    def get_accuracy(self) -> float:
        """Calculate overall accuracy percentage."""
        if self.total_exercises_completed == 0:
            return 0.0
        return (self.total_correct_answers / self.total_exercises_completed) * 100

    def to_dict(self) -> dict[str, Any]:
        """Serialize state to dict for persistence."""
        return {
            "user_id": self.user_id,
            "session_id": self.session_id,
            "current_lesson": self.current_lesson,
            "current_mode": self.current_mode,
            "learned_items": self.learned_items,
            "lesson_history": self.lesson_history,
            "conversation_history": [
                {
                    "role": msg.role,
                    "content": msg.content,
                    "timestamp": msg.timestamp.isoformat(),
                    "metadata": msg.metadata,
                }
                for msg in self.conversation_history
            ],
            "pending_exercise": self.pending_exercise.__dict__ if self.pending_exercise else None,
            "awaiting_user_answer": self.awaiting_user_answer,
            "last_agent": self.last_agent,
            "next_agent": self.next_agent,
            "cached_vocab_words": self.cached_vocab_words,
            "cached_grammar_content": self.cached_grammar_content,
            "lesson_initialized": self.lesson_initialized,
            "preloaded_grammar_rules": self.preloaded_grammar_rules,
            "total_exercises_completed": self.total_exercises_completed,
            "total_correct_answers": self.total_correct_answers,
            "session_start_time": self.session_start_time.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SystemState":
        """Deserialize state from dict."""
        learned_items = data.get("learned_items", [])
        state = cls(
            user_id=data["user_id"],
            session_id=data["session_id"],
            current_lesson=data.get("current_lesson", 1),
            current_mode=data.get("current_mode", "vocabulary"),
            learned_items=learned_items,
            lesson_history=data.get("lesson_history", []),
            awaiting_user_answer=data.get("awaiting_user_answer", False),
            last_agent=data.get("last_agent", ""),
            next_agent=data.get("next_agent", "agent1"),
            cached_vocab_words=data.get("cached_vocab_words", []),
            cached_grammar_content=data.get("cached_grammar_content", {}),
            lesson_initialized=data.get("lesson_initialized", False),
            preloaded_grammar_rules=data.get("preloaded_grammar_rules", {}),
            total_exercises_completed=data.get("total_exercises_completed", 0),
            total_correct_answers=data.get("total_correct_answers", 0),
        )

        # Rebuild the set from learned_items for O(1) lookups
        state._learned_items_set = set(learned_items)

        # Restore conversation history
        if "conversation_history" in data:
            history = data["conversation_history"]
            if history and isinstance(history[0], Message):
                # Already Message objects (from LangGraph)
                state.conversation_history = history
            elif history and isinstance(history[0], dict):
                # Dicts that need conversion
                state.conversation_history = []
                for msg in history:
                    timestamp = msg.get("timestamp")
                    if isinstance(timestamp, str):
                        timestamp = datetime.fromisoformat(timestamp)
                    state.conversation_history.append(
                        Message(
                            role=msg["role"],
                            content=msg["content"],
                            timestamp=timestamp or datetime.now(),
                            metadata=msg.get("metadata", {}),
                        )
                    )

        # Restore pending exercise
        if data.get("pending_exercise"):
            exercise_data = data["pending_exercise"]
            if isinstance(exercise_data, Exercise):
                state.pending_exercise = exercise_data
            else:
                state.pending_exercise = Exercise(**exercise_data)

        # Restore session start time
        if "session_start_time" in data:
            start_time = data["session_start_time"]
            if isinstance(start_time, str):
                state.session_start_time = datetime.fromisoformat(start_time)
            elif isinstance(start_time, datetime):
                state.session_start_time = start_time

        return state


def create_initial_state(lesson_number: int, user_id: str = "user_1") -> SystemState:
    """
    Create initial state for lesson start - single source of truth.

    This is the canonical way to create state for a new lesson.
    Used by app.py and all tests to ensure consistency.

    Args:
        lesson_number: Lesson number to start
        user_id: User identifier (default: "user_1")

    Returns:
        SystemState configured for lesson start
    """
    return SystemState(
        user_id=user_id,
        session_id=f"session_{lesson_number}_{datetime.now().timestamp()}",
        current_lesson=lesson_number,
        conversation_history=[],
        next_agent="agent1",
        last_agent="",
    )
